# In 'build', we will use cmake & make to build woo..
variables:
  CACHE_FALLBACK_KEY: wo-build-master

build_release_win32:
  stage: build
  script:
    - echo "%CI_COMMIT_SHA%" > src/wo_info.hpp
    - git submodule update --init --recursive --force
    - if not exist build ( mkdir build )
    - cd build
    - del CMakeCache.txt
    - cmake .. -DWO_MAKE_OUTPUT_IN_SAME_PATH=ON -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DBUILD_SHARED_LIBS=ON
    - MSBuild driver/woodriver.vcxproj -p:Configuration=Release -m
    - cd ..
  artifacts:
    name: win32-wo-build-release-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    paths:
      - build/Release/woodriver.exe
      - build/Release/libwoo.dll
    expire_in: 1 week
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    when: on_success
    key: wo-build-release-win32-$CI_COMMIT_REF_SLUG
    paths:
        - "build/*"
  tags:
    - winserver22

build_release:
  stage: build
  script:
    - echo "\"$CI_COMMIT_SHA\"" > src/wo_info.hpp
    - git submodule update --init --recursive --force
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - rm -f CMakeCache.txt
    - cmake .. -DWO_MAKE_OUTPUT_IN_SAME_PATH=ON -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DBUILD_SHARED_LIBS=ON
    - make -j 4
    - cd ..
  artifacts:
    name: ubuntu-wo-build-release-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    paths:
      - build/woodriver
      - build/libwoo.so
    expire_in: 1 week
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    when: on_success
    key: wo-build-release-$CI_COMMIT_REF_SLUG
    paths:
        - "build/*"
  tags:
    - ubuntu20

test_coverage_debug:
  stage: test
  except: 
    - tags
  script:
    - sudo sysctl -p
    - ulimit -c unlimited
    - echo "\"$CI_COMMIT_SHA\"" > src/wo_info.hpp
    - git submodule update --init --recursive --force
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - rm -f CMakeCache.txt
    - cmake .. -DWO_MAKE_OUTPUT_IN_SAME_PATH=ON -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_SHARED_LIBS=ON -DWO_BUILD_FOR_COVERAGE_TEST=ON
    - make -j 4
    - cd ..
    # Begin coverage test
    - cd test
    - sudo baozi install --nowoo
    - sudo chmod 777 ./pkg
    - sudo chmod 777 .
    - cd ..
    - sudo ./build/woodriver_debug test/test_all.wo --enable-ctrlc-debug 0 --enable-jit 1
    - cd build/src/CMakeFiles/woolang.dir
    - sudo gcov -b -l -p -c *.gcno
    - cd ../../../../
    - pwd
    - sudo sudo gcovr . -r ./src -g -k
    - sudo gcovr . -r ./src -g -k --html --html-details -o report.html
  artifacts:
    name: ubuntu-wo-coverage-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    paths:
      - build/woodriver_debug
      - build/libwoo_debug.so
      - build/*.gcov
      - "*.html"
      - core
    expire_in: 1 week
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    when: on_success
    key: wo-build-coverage-$CI_COMMIT_REF_SLUG
    paths:
        - "build/*"
  tags:
    - ubuntu20

# run tests using the binary built before

test_release:
  stage: test
  except: 
    - tags
  script:
    - sudo sysctl -p
    - ulimit -c unlimited
    - cd test
    - sudo baozi install --nowoo
    - sudo chmod 777 ./pkg
    - sudo chmod 777 .
    - cd ..
    - ./build/woodriver test/test_all.wo --enable-ctrlc-debug 0 --enable-jit 0 -o test_nojit.woo
    - ./build/woodriver test_nojit.woo --enable-ctrlc-debug 0 --enable-jit 0
    - ./build/woodriver test/test_all.wo --enable-ctrlc-debug 0 --enable-jit 0
    - ./build/woodriver test/test_all.wo --enable-ctrlc-debug 0 --enable-jit 1
  tags:
    - ubuntu20
  artifacts:
    name: "test-report-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    paths:
      - core
    when: on_failure
    expire_in: 1 week
  # cache:
  #   key: wo-build-debug-$CI_COMMIT_REF_SLUG
  #   policy: pull
  #   paths:
  #       - "build/*"
  dependencies:
    - build_release
    
test_memory_debug:
  stage: test
  only: 
    - tags
  script:
    - sudo sysctl -p
    - ulimit -c unlimited
    - git submodule update --init --recursive --force
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - rm -f CMakeCache.txt
    - cmake .. -DWO_MAKE_OUTPUT_IN_SAME_PATH=ON -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_SHARED_LIBS=ON
    - make -j 4
    - cd ..
    # Begin coverage test
    - cd test
    - sudo baozi install --nowoo
    - sudo chmod 777 ./pkg
    - sudo chmod 777 .
    - cd ..
    - sudo valgrind --tool=memcheck --leak-check=yes --show-reachable=yes ./build/woodriver_debug test/test_all.wo --enable-ctrlc-debug 0 --enable-jit 1
  artifacts:
    name: ubuntu-wo-coverage-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    paths:
      - build/woodriver_debug
      - build/libwoo_debug.so
    expire_in: 1 week
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    when: on_success
    key: wo-build-coverage-$CI_COMMIT_REF_SLUG
    paths:
        - "build/*"
  tags:
    - ubuntu20

# run tests using the binary built before

test_memory_release:
  stage: test
  only: 
    - tags
  script:
    - sudo sysctl -p
    - ulimit -c unlimited
    - cd test
    - sudo baozi install --nowoo
    - sudo chmod 777 ./pkg
    - sudo chmod 777 .
    - cd ..
    - sudo valgrind --tool=memcheck --leak-check=yes --show-reachable=yes ./build/woodriver test/test_all.wo --enable-ctrlc-debug 0 --enable-jit 0
    - sudo valgrind --tool=memcheck --leak-check=yes --show-reachable=yes ./build/woodriver test/test_all.wo --enable-ctrlc-debug 0 --enable-jit 1
  tags:
    - ubuntu20
  artifacts:
    name: "test-report-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    paths:
      - core
    when: on_failure
    expire_in: 1 week
  # cache:
  #   key: wo-build-debug-$CI_COMMIT_REF_SLUG
  #   policy: pull
  #   paths:
  #       - "build/*"
  dependencies:
    - build_release
    
