# In 'build', we will use cmake & make to build woo..
variables:
  CACHE_FALLBACK_KEY: wo-build-master

build_release:
  stage: build
  script:
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - rm -f CMakeCache.txt
    - cmake .. -DWO_MAKE_OUTPUT_IN_SAME_PATH=ON -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DBUILD_SHARED_LIBS=ON
    - make
    - cd ..
  artifacts:
    name: ubuntu-wo-build-release-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    paths:
      - build/woodriver
      - build/libwoo.so
    expire_in: 1 week
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    when: on_success
    key: wo-build-release-$CI_COMMIT_REF_SLUG
    paths:
        - "build/*"
  tags:
    - ubuntu1804_cicd

build_debug:
  stage: build
  script:
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - rm -f CMakeCache.txt
    - cmake .. -DWO_MAKE_OUTPUT_IN_SAME_PATH=ON -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_SHARED_LIBS=ON -WO_BUILD_FOR_COVERAGE_TEST=ON
    - make
    - cd ..
  artifacts:
    name: ubuntu-wo-build-debug-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    paths:
      - build/woodriver_debug
      - build/libwoo_debug.so
      - build/src/CMakeFiles/woolang.dir/*.gcda
      - build/src/CMakeFiles/woolang.dir/*.gcno
    expire_in: 1 week
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
    when: on_success
    key: wo-build-debug-$CI_COMMIT_REF_SLUG
    paths:
        - "build/*"
  tags:
    - ubuntu1804_cicd

# run tests using the binary built before

test_debug_and_release:
  stage: test
  script:
    - ./build/woodriver test/test_all.wo --coroutine-thread-count 2 --enable-ctrlc-debug 0
    - ./build/woodriver_debug test/test_all.wo --coroutine-thread-count 2 --enable-ctrlc-debug 0
    - gcov build/src/CMakeFiles/woolang.dir/*.gcda
  tags:
    - ubuntu1804_cicd
  artifacts:
    name: "test-report-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    paths:
      - core
      - build/src/CMakeFiles/woolang.dir/*.gcda
    expire_in: 1 week
  dependencies:
    - build_release
    - build_debug
