#pragma once
// This file using to store compiler/lexer's error informations.
// Here will be 

#define WO_LANG_EN 0
#define WO_LANG_ZH_CN 1

#define WO_MAX_ERROR_COUNT 100

#ifndef WO_USED_LANGUAGE
#   define WO_USED_LANGUAGE WO_LANG_ZH_CN
#endif


#define WO_HERE L"此处"
#define WO_SEE_HERE L"参见"
#define WO_SEE_ALSO L"另见"

#define WO_TERM_EXCEPTED L"应当是"

#define WO_TOO_MANY_ERROR(count) L"报告的错误数量太多, 仅显示 " + std::to_wstring(count) +  L" 条, 终止"

// PASS LEXER
#define WO_ERR_MISMATCH_ANNO_SYM L"不匹配的注释符"
#define WO_ERR_UNEXCEPT_CH_AFTER_CH L"未预料的字符 '%lc' 位于 '%lc' 之后"
#define WO_ERR_UNEXCEPT_CH_AFTER_CH_EXCEPT_CH L"未预料的字符 '%lc' 位于 '%lc' 之后, 期待 '%lc'"
#define WO_ERR_UNEXCEPT_EOF L"未预料的文件尾"
#define WO_ERR_UNEXCEPT_TOKEN L"未预料的: "
#define WO_ERR_ILLEGAL_LITERAL L"非法的字面常量"
#define WO_ERR_UNKNOW_OPERATOR_STR L"未知运算符: '%ls'"
#define WO_ERR_UNEXCEPTED_EOL_IN_CHAR L"在字符常量中发现换行符"
#define WO_ERR_UNEXCEPTED_EOL_IN_STRING L"在字符串常量中发现换行符"
#define WO_ERR_UNKNOWN_REPEAT_MACRO_DEFINE L"重复的宏定义 '%ls'"
#define WO_ERR_UNKNOWN_PRAGMA_COMMAND L"未知的预处理指令 '%ls'"
#define WO_ERR_FAILED_TO_COMPILE_MACRO_CONTROLOR L"宏控制器编译失败"
#define WO_ERR_FAILED_TO_RUN_MACRO_CONTROLOR L"宏 '%ls' 运行发生了错误: %ls"
#define WO_ERR_UNKNOW_ESCSEQ_BEGIN_WITH_CH L"以 '%lc' 开头的未知转义序列."
#define WO_ERR_INVALID_TOKEN_MACRO_CONTROLOR L"宏 '%ls' 生成了非法的词法序列"
#define WO_ERR_RECURSIVE_FORMAT_STRING_IS_INVALID L"嵌套格式化字符串是不被允许的"
#define WO_ERR_HERE_SHOULD_HAVE L"缺少 '%ls'"
#define WO_ERR_LEXER_ERR_UNKNOW_NUM_BASE L"词法错误, 未知的常量基数"
#define WO_ERR_LEXER_ERR_UNKNOW_BEGIN_CH L"未知的字符: '%lc'"
#define WO_ERR_UNEXCEPT_AST_NODE_TYPE L"未预料到的语法树节点类型: 应当是语法树节点或标识符"
#define WO_ERR_SHOULD_BE_AST_BASE L"语法分析时发生未知错误: 未知节点类型"
#define WO_ERR_UNABLE_RECOVER_FROM_ERR L"无法从当前错误中恢复, 编译终止"

// PASS AST BUILDER
#define WO_ERR_CANNOT_OPEN_FILE L"无法打开文件: '%ls'"
#define WO_ERR_ARG_DEFINE_AFTER_VARIADIC L"在 '...' 之后不应该有其他参数"
#define WO_ERR_ARG_DEFINE_AFTER_EXPAND_VECARR L"在展开数组之后不能传入其他参数"
#define WO_ERR_UNKNOWN_TYPE L"未知或不完整的类型"
#define WO_ERR_REDEFINED L"在当前作用域中重复定义了 '%ls'"
#define WO_ERR_REPEAT_MEMBER_NAME L"重复的成员: '%ls'"
#define WO_ERR_REPEAT_ATTRIBUTE L"重复出现的属性"
#define WO_ERR_FAILED_TO_CREATE_TUPLE_WITH_VAARG L"元组类型中不允许出现 '...'"
#define WO_ERR_INVALID_KEY_EXPR L"创建映射时遇到了非法的键表达式"
#define WO_ERR_UNKNOWN_MACRO_NAMED L"未定义的宏: '%ls'"
#define WO_ERR_UNKNOWN_EXTERN_ATTRIB L"未知的外部函数说明符: '%ls'"
#define WO_ERR_COMPILER_DISABLED L"编译器未启用"
#define WO_ERR_CANNOT_START_NAMESPACE L"不允许在这里定义命名空间"
#define WO_ERR_CANNOT_USING_UNSAFE L"不允许 'using' 名为 'unsafe' 的命名空间"

// PASS0_1 TYPE CHECK PARSE
#define WO_ERR_UNFOUND_TYPE_NAMED L"没有找到名为 '%ls' 的类型"
#define WO_ERR_UNFOUND_VARIABLE_NAMED L"没有找到名为 '%ls' 的常量、变量或函数"
#define WO_ERR_UNEXPECTED_TEMPLATE_COUNT L"目标期待有且仅有 '%zu' 个泛型参数"
#define WO_ERR_EXPECTED_TEMPLATE_ARGUMENT L"'%ls' 是一个泛型目标"
#define WO_ERR_UNEXPECTED_TEMPLATE_ARGUMENT L"'%ls' 不是一个泛型目标"
#define WO_ERR_UNEXPECTED_MATCH_TYPE_FOR_TUPLE L"匹配期待一个元组"
#define WO_ERR_UNEXPECTED_MATCH_COUNT_FOR_TUPLE L"匹配期待一个包含 '%zu' 个元素的元组, 但给定的元组包含 '%zu' 个元素"
#define WO_ERR_VALUE_TYPE_DETERMINED_FAILED L"表达式类型未确定"
#define WO_ERR_TYPE_DETERMINED_FAILED L"类型未确定"
#define WO_ERR_TYPE_NAMED_DETERMINED_FAILED L"类型 '%ls' 暂未决, 无法进行类型检查"
#define WO_ERR_RECURSIVE_TEMPLATE_INSTANCE L"类型推断递归地依赖了正在具体化的泛型实例"
#define WO_ERR_RECURSIVE_EVAL_PASS1 L"递归地依赖了自身"
#define WO_ERR_CONSTRAINT_SHOULD_BE_CONST L"约束项应当是一个常量表达式"
#define WO_ERR_CONSTRAINT_SHOULD_BE_BOOL L"约束项的值类型应该是 'bool'"
#define WO_ERR_CONSTRAINT_FAILED L"约束项不满足"
#define WO_ERR_NOT_IN_REIFICATION_TEMPLATE_FUNC L"在没有泛型指明或推导语境下尝试具体化匿名的泛型函数"
#define WO_ERR_UNMATCHED_RETURN_TYPE_NAMED L"函数的实际返回类型 '%ls' 与标注或推导的类型 '%ls' 不匹配"
#define WO_ERR_UNMATCHED_ARRAY_ELEMENT_TYPE_NAMED L"元素的类型 '%ls' 与先前推导的 '%ls' 不匹配"
#define WO_ERR_UNMATCHED_DICT_KEY_TYPE_NAMED L"键元素的类型 '%ls' 与先前推导的 '%ls' 不匹配"
#define WO_ERR_UNMATCHED_DICT_VALUE_TYPE_NAMED L"值元素的类型 '%ls' 与先前推导的 '%ls' 不匹配"
#define WO_ERR_UNINDEXABLE_TYPE_NAMED L"不能作为容器的类型 '%ls'"
#define WO_ERR_CANNOT_INDEX_TYPE_WITH_TYPE L"容器类型 '%ls' 不接受索引类型 '%ls'"
#define WO_ERR_CANNOT_INDEX_STRUCT_WITH_NON_CONST L"结构体类型不接受非常量索引"
#define WO_ERR_CANNOT_INDEX_TUPLE_WITH_NON_CONST L"元组类型不接受非常量索引"
#define WO_ERR_ONLY_EXPAND_ARRAY_VEC_AND_TUPLE L"只有数组、向量和元组可以展开, 但这里是 '%ls'"
#define WO_ERR_ONLY_EXPAND_TUPLE L"只允许展开元组, 但实际尝试展开 '%ls'"
#define WO_ERR_STRUCT_DONOT_HAVE_MAMBER_NAMED L"结构体类型 '%ls' 没有名为 '%ls' 的成员"
#define WO_ERR_TUPLE_INDEX_OUT_OF_RANGE L"元组类型 '%ls' 只有 %zu 个元素, 但索引 %zu 超出了范围"
#define WO_ERR_PATTERN_VARIABLE_SHOULD_BE_MUTABLE L"被赋值的变量应当可变"
#define WO_ERR_PATTERN_INDEX_SHOULD_BE_MUTABLE_TYPE L"不能向不可变索引结果赋值"
#define WO_ERR_CANNOT_CAST_TYPE_TO_TYPE L"无法将类型 '%ls' 转换为 '%ls'"
#define WO_ERR_FAILED_TO_DEDUCE_TEMPLATE_TYPE L"泛型参数自动推导失败"
#define WO_ERR_NOT_ALL_TEMPLATE_ARGUMENT_DETERMINED L"泛型参数 <%ls> 未能推导"
#define WO_ERR_TARGET_TYPE_IS_NOT_A_FUNCTION L"调用的目标类型 '%ls' 不是一个函数"
#define WO_ERR_ARGUMENT_TOO_MUCH L"参数过多"
#define WO_ERR_ARGUMENT_TOO_LESS L"参数过少"
#define WO_ERR_CANNOT_ACCEPTABLE_TYPE_NAMED L"不接受类型 '%ls', 应当是 '%ls'"
#define WO_ERR_CANNOT_CAST_TYPE_NAMED_FROM_DYNMAIC L"无法在运行时从动态类型确认类型 '%ls'"
#define WO_ERR_TYPE_NAMED_IS_NOT_STRUCT L"类型 '%ls' 不是结构体类型"
#define WO_ERR_REPEATED_FIELD_NAMED L"重复的字段名 '%ls'"
#define WO_ERR_NOT_ALL_FIELD_INITIALIZED L"存在未初始化的结构体字段"
#define WO_ERR_TOO_MUCH_FIELD_INITIALIZED L"结构体初始项的数量太多"
#define WO_ERR_AMBIGUOUS_TARGET_NAMED L"'%ls' 不明确, 编译器假定其在下文中指代的是 '%ls'"
#define WO_ERR_DIFFERENT_TYPE_IN_BINARY L"运算符左右两侧的值类型不适合此运算"
#define WO_ERR_UNACCEPTABLE_TYPE_IN_OPERATE L"'%ls' 类型的操作数不能用于此计算"
#define WO_ERR_UNACCEPTABLE_TYPE_IN_COND L"表达式类型不应该是 '%ls', 条件表达式的类型只能是 'bool'"
#define WO_ERR_UNEXPECTED_PACKEDARGS L"变长参数包只能出现在变长参数的函数体之内"
#define WO_ERR_UNEXPECTED_MACTHING_TYPE L"'match' 语句只支持匹配共用体类型, 但这里是 '%ls'"
#define WO_ERR_TAKEPLACE_PATTERN_MATCHED L"占位模式此前已经被使用, 不能在占位分支之后匹配其他模式"
#define WO_ERR_ALL_CASES_SHOULD_BE_MATCHED L"'match' 语句需要穷尽所有可能的分支"
#define WO_ERR_UNEXISTS_CASE_NAMED_IN_MATCH L"在 'match' 语句中不存在名为 '%ls' 的匹配项"
#define WO_ERR_EXISTS_CASE_NAMED_IN_MATCH L"匹配项 '%ls' 已经存在于 'match' 语句中"
#define WO_ERR_HAVE_NOT_VALUE_CASE_IN_MATCH L"类型 `%ls` 的匹配项 '%ls' 需要包含值"
#define WO_ERR_HAVE_VALUE_CASE_IN_MATCH L"类型 `%ls` 的匹配项 '%ls' 不应该包含值"
#define WO_ERR_FAILED_REIFICATION_CAUSED_BY L"用泛型参数: <%ls> 具体化泛型实例 '%ls' 失败"
#define WO_ERR_UNABLE_CAPTURE_IN_RECURSIVE_FUNC L"递归函数不允许捕获变量"
#define WO_ERR_STRING_INDEX_OUT_OF_RANGE L"字符串索引超出范围"
#define WO_ERR_SYMBOL_IS_PRIVATE L"'%ls' 是私有的, 只能在 '%ls' 中访问"
#define WO_ERR_SYMBOL_IS_PROTECTED L"'%ls' 是受保护的, 只能在命名空间 '%ls' 内访问"
#define WO_ERR_SOURCE_MUST_BE_IMPORTED L"'%ls' 来自未导入的脚本 '%ls'"
#define WO_ERR_STRUCT_FIELD_IS_PRIVATE L"结构体字段 '%ls' 是私有的, 只能在 '%ls' 中访问"
#define WO_ERR_STRUCT_FIELD_IS_PROTECTED L"结构体字段 '%ls' 是受保护的, 只能在命名空间 '%ls' 内访问"
#define WO_ERR_UNABLE_TO_MIX_TYPES L"无法推导出同时接受 '%ls' 和 '%ls' 的类型"
#define WO_ERR_UNACCEPTABLE_MUTABLE L"明确要求类型为不可变的，但收到的是 '%ls'"
#define WO_ERR_CANNOT_USE_BUILTIN_TYPENAME_HERE L"内置类型 '%ls' 的名称不能被直接使用"
#define WO_ERR_BAD_DIV_ZERO L"除数不能为零"
#define WO_ERR_BAD_DIV_OVERFLOW L"除法溢出"

// PASS0_1 TYPE CHECK PARSE(INFO)
#define WO_INFO_MAYBE_NAMED_DEFINED_HERE L"可能是这里的 '%ls'"
#define WO_INFO_MAYBE_NAMED_DEFINED_IN_COMPILER L"可能是编译器内部定义的 '%ls'"
#define WO_INFO_SYMBOL_NAMED_DEFINED_HERE L"'%ls' 的定义"
#define WO_INFO_TYPE_NAMED_BEFORE_DIRECT_SIGN L"首个参数的类型是 '%ls'"
#define WO_INFO_THIS_VALUE_IS_TYPE_NAMED L"表达式的类型是 '%ls'"
#define WO_INFO_CAPTURED_VARIABLE_USED_HERE L"捕获了来自函数外部的 '%ls'"
#define WO_INFO_TRYING_REFILL_TEMPLATE_ARGUMENT L"尝试为类型 '%ls'(通过类型别名 '%ls' 指示) 重新提供泛型参数"
#define WO_INFO_OLD_FUNCTION_RETURN_TYPE_IS L"此前函数的返回类型被推断为 '%ls'"

// PASSIR BYTECODE GENERATOR
#define WO_ERR_NON_VOID_TYPE_EXPR_AS_STMT L"非 'void' 类型 (此处是 '%ls') 的表达式不能作为语句, 这可能导致表达式的结果被意外忽略"
#define WO_ERR_VARIBALE_STORAGE_NOT_DETERMINED L"依赖了尚未完成初始化的变量 '%ls'"
#define WO_ERR_UNABLE_TO_FIND_EXTERN_FUNCTION L"无法在库 '%ls' 找到外部函数 '%ls'"
#define WO_ERR_CANNOT_UNPACK_HERE L"只能在函数的参数列表或元组元素列表中展开参数包"
#define WO_ERR_BAD_BREAK L"无效的 'break' 语句"
#define WO_ERR_BAD_CONTINUE L"无效的 'continue' 语句"
#define WO_ERR_UNSED_VARIABLE L"声明了局部的 '%ls', 但从未使用"

// PASSIR BYTECODE GENERATOR(INFO)
#define WO_INFO_BAD_LABEL_NAMED L"无法找到标签为 `%ls` 的循环"
#define WO_INFO_IN_FUNCTION_NAMED L"在函数 '%ls' 中"